#!/bin/bash

#Name: word_freq.sh
#Desc: Find out frequency of words in a file
#$#=Special variable which expands the number of arguments such as $1,$2 and so on..





if [ $# -ne 1 ];
then
  echo "Usage: $0 filename";
  exit -1
fi

echo "******************************"
cat $1 |tr -s ' ' '\n' |  sort | uniq -c  
#cat $1 | tr -s ' ' '\n' | sort | uniq -c | awk '{print $2 " = "$1}' 

